on: push

jobs:
  run:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint-all
          - test-ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16.5'
      - name: Install dependencies
        run: make setup
      - name: make ${{ matrix.target }}
        run: make ${{ matrix.target }}
